In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# Arrays

In [3]:
d1 = np.array([1,2,3,4,5])

In [4]:
d1

array([1, 2, 3, 4, 5])

In [5]:
d1.ndim

1

In [7]:
d2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [8]:
d2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [9]:
d2.ndim

2

In [12]:
d3 = [
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
]

In [13]:
d3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [16]:
marks = [
    [ # class 1
        [80,90],
        [70,80],
        [60,75]
    ],
    [ # class 2
        [88,92],
        [76,81],
        [95,88]
    ],
    [ # class 3
        [88,92],
        [76,81],
        [95,88]
    ]
]

In [17]:
marks

[[[80, 90], [70, 80], [60, 75]],
 [[88, 92], [76, 81], [95, 88]],
 [[88, 92], [76, 81], [95, 88]]]

In [18]:
d3 = np.array(marks)

In [19]:
d3

array([[[80, 90],
        [70, 80],
        [60, 75]],

       [[88, 92],
        [76, 81],
        [95, 88]],

       [[88, 92],
        [76, 81],
        [95, 88]]])

In [20]:
d3.ndim

3

In [23]:
np.random.randint(10,50,5)

array([43, 14, 27, 10, 29])

In [24]:
names = ['X','Y','Z','A']

In [30]:
np.random.choice(names)

'X'

In [34]:
nums = [1,2,3,4,5,6]

In [35]:
np.random.shuffle(nums)

In [36]:
nums

[4, 1, 6, 5, 3, 2]

In [40]:
df = np.array([10,20,30,40,50])

In [41]:
df

array([10, 20, 30, 40, 50])

In [42]:
df[0]

10

In [43]:
df[3]

40

In [44]:
a2 = np.array([[1,2,3],[4,5,6]])

In [45]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# [row][column]
a2[1][2]

6

In [47]:
a2[0][2]

3

In [48]:
a2[1][1]

5